<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Btech.Package.Cache" Version="3.11.82" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IQT_FSD_2026.Domain\IQT_FSD_2026.Domain.csproj" />
    <ProjectReference Include="..\IQT_FSD_2026.Infrastructure\IQT_FSD_2026.Infrastructure.csproj" />
  </ItemGroup>

</Project>
