# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: $(Build.BuildId)

trigger:
  branches:
    include:
      - master # Production
      - staging # stg
  tags:
    include:
      - v*.*.*

pool:
  vmImage: ubuntu-latest
  

variables:
  - group: Btech-inventory
  - name: IMAGE_NAME
    value: "inventory-api"
  - name: ECRNAME
    value: "inventory-api"
  - name: IMAGE_TAG
    value: "$(environment)-$(Build.SourceVersionShort)-$(Build.BuildId)"
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/master') }}:
    - name: environment
      value: "prod"
  - ${{ elseif eq(variables['Build.SourceBranch'], 'refs/heads/staging') }}:
    - name: environment
      value: "stg"

## Fetch short commit code
steps:
- script: |
    export CommitCode=$(echo $(Build.SourceVersion) | cut -c1-7 )
    echo "##vso[task.setvariable variable=Build.SourceVersionShort;sOutput=true;]$CommitCode"
  displayName: 'fetch commit short code'

## Docker build
- script: docker build -t $(IMAGE_NAME) .
  displayName: 'docker image build  '

## Image push to ECR
- task: ECRPushImage@1
  inputs:
    awsCredentials: '$(CONNECTION)'
    regionName: '$(REGION)'
    imageSource: 'imagename'
    sourceImageName: '$(IMAGE_NAME)'
    repositoryName: '$(ECRNAME)'
    pushTag: '$(IMAGE_TAG)'
  displayName: 'push to ecr'

## Clone deployment repo
- script: |
    git clone https://$(GITHUB_TOKEN)@$(TARGET_GITHUB_REPO) repo
  displayName: "Clone Target GitHub Repo"
 
## Replace image_tag
- script: |
    cd repo/environments/$(environment)
    echo "IMAGE_TAG is:" $(IMAGE_TAG)
    sed -i 's/^\(image_tag[[:space:]]*=[[:space:]]*\)".*"/\1"'"$(IMAGE_TAG)"'"/' terraform.tfvars
    cat terraform.tfvars
  displayName: "Update terraform.tfvars with IMAGE_TAG"

## Commit and push the code
- script: |
    cd repo/environments/$(environment)
    git config user.email "devops-op@Btech.co"
    git config user.name "Azure CI"
    git add terraform.tfvars
    git commit -m "Updated image_tag to $(IMAGE_TAG)"
    git push https://$(GITHUB_TOKEN)@$(TARGET_GITHUB_REPO) "main"
  displayName: "Commit and Push terraform.tfvars Update"
